import Header from '../../../../_components/Header/JobInsertionDetailHeader/JobInsertionDetailHeader'
import Footer from '../../../../_components/Footer/JobInsertionDetailFooter/JobInsertionDetailFooter'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {
  return (
    <>
      <Header></Header>
      {children}
      <Footer></Footer>
    </>
  )
}
