import Link from "next/link";

export default function JobInsertionsPage() {

    return (
        <div>
            <h1>Job Insertions Page</h1>
            <p>Generated by Next.js</p>
            <Link href="/">Home</Link><br />
            <Link href="/job-insertions/1">JI-1</Link><br />
            <Link href="/job-insertions/2">JI-2</Link><br />
            <Link href="/job-insertions/3">JI-3</Link>
        </div>
    )
}